-- AlterTable
ALTER TABLE "detail_permintaan" ADD COLUMN     "ID_PENGEMBALIAN" TEXT;

-- AlterTable
ALTER TABLE "permintaan" ADD COLUMN     "ID_PENGEMBALIAN" TEXT;

-- CreateTable
CREATE TABLE "pengembalian" (
    "ID_PENGEMBALIAN" TEXT NOT NULL,
    "TGL_PENGEMBALIAN" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_PERMINTAAN" TEXT,

    CONSTRAINT "pengembalian_pkey" PRIMARY KEY ("ID_PENGEMBALIAN")
);

-- CreateIndex
CREATE UNIQUE INDEX "pengembalian_ID_PERMINTAAN_key" ON "pengembalian"("ID_PERMINTAAN");

-- AddForeignKey
ALTER TABLE "detail_permintaan" ADD CONSTRAINT "detail_permintaan_ID_PENGEMBALIAN_fkey" FOREIGN KEY ("ID_PENGEMBALIAN") REFERENCES "pengembalian"("ID_PENGEMBALIAN") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pengembalian" ADD CONSTRAINT "pengembalian_ID_PERMINTAAN_fkey" FOREIGN KEY ("ID_PERMINTAAN") REFERENCES "permintaan"("ID_PERMINTAAN") ON DELETE CASCADE ON UPDATE CASCADE;
