-- CreateTable
CREATE TABLE `alat` (
    `ID_ALAT` VARCHAR(10) NOT NULL,
    `NAMA_ALAT` VARCHAR(30) NULL,
    `JUMLAH_ALAT` INTEGER NOT NULL,
    `UNIT_ALAT` VARCHAR(35) NULL,
    `STATUS_KELAYAKAN` VARCHAR(35) NULL,

    PRIMARY KEY (`ID_ALAT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `bahan` (
    `ID_BAHAN` VARCHAR(10) NOT NULL,
    `NAMA_BAHAN` VARCHAR(30) NULL,
    `STOCK_BAHAN` VARCHAR(35) NULL,
    `UNIT_BAHAN` VARCHAR(10) NULL,

    PRIMARY KEY (`ID_BAHAN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `detail_permintaan` (
    `ID_DETAIL_PERMINTAAN` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PERMINTAAN` INTEGER NULL,
    `ID_ALAT` VARCHAR(10) NULL,
    `ID_BAHAN` VARCHAR(10) NULL,
    `JUMLAH_ALAT` VARCHAR(30) NULL,
    `JUMLAH_BAHAN` VARCHAR(30) NULL,

    INDEX `FK_RELATIONSHIP_3`(`ID_ALAT`),
    INDEX `FK_RELATIONSHIP_4`(`ID_PERMINTAAN`),
    INDEX `FK_RELATIONSHIP_5`(`ID_BAHAN`),
    PRIMARY KEY (`ID_DETAIL_PERMINTAAN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `permintaan` (
    `ID_PERMINTAAN` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NULL,
    `TGL_PERMINTAAN` DATE NULL,
    `STATUS` VARCHAR(30) NULL,

    INDEX `FK_RELATIONSHIP_1`(`ID_USER`),
    PRIMARY KEY (`ID_PERMINTAAN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `ID_USER` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(35) NULL,
    `USERNAME` VARCHAR(25) NULL,
    `PASSWORD` VARCHAR(25) NULL,
    `ROLE` VARCHAR(30) NULL,
    `REGISTER` DATE NULL,

    PRIMARY KEY (`ID_USER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `detail_permintaan` ADD CONSTRAINT `FK_RELATIONSHIP_3` FOREIGN KEY (`ID_ALAT`) REFERENCES `alat`(`ID_ALAT`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `detail_permintaan` ADD CONSTRAINT `FK_RELATIONSHIP_4` FOREIGN KEY (`ID_PERMINTAAN`) REFERENCES `permintaan`(`ID_PERMINTAAN`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `detail_permintaan` ADD CONSTRAINT `FK_RELATIONSHIP_5` FOREIGN KEY (`ID_BAHAN`) REFERENCES `bahan`(`ID_BAHAN`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `permintaan` ADD CONSTRAINT `FK_RELATIONSHIP_1` FOREIGN KEY (`ID_USER`) REFERENCES `user`(`ID_USER`) ON DELETE RESTRICT ON UPDATE RESTRICT;
