-- CreateTable
CREATE TABLE "armada" (
    "ID_ARMADA" TEXT NOT NULL,
    "NAMA_ARMADA" TEXT NOT NULL,

    CONSTRAINT "armada_pkey" PRIMARY KEY ("ID_ARMADA")
);

-- CreateTable
CREATE TABLE "transportasi" (
    "ID_TRANSPORTASI" TEXT NOT NULL,
    "NAMA_TRANSPORTASI" TEXT NOT NULL,
    "JENIS_TRANSPORTASI" TEXT NOT NULL,
    "ID_PERMINTAAN" TEXT,
    "ID_ARMADA" TEXT NOT NULL,

    CONSTRAINT "transportasi_pkey" PRIMARY KEY ("ID_TRANSPORTASI")
);

-- CreateIndex
CREATE UNIQUE INDEX "transportasi_ID_PERMINTAAN_key" ON "transportasi"("ID_PERMINTAAN");

-- AddForeignKey
ALTER TABLE "transportasi" ADD CONSTRAINT "transportasi_ID_ARMADA_fkey" FOREIGN KEY ("ID_ARMADA") REFERENCES "armada"("ID_ARMADA") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transportasi" ADD CONSTRAINT "transportasi_ID_PERMINTAAN_fkey" FOREIGN KEY ("ID_PERMINTAAN") REFERENCES "permintaan"("ID_PERMINTAAN") ON DELETE CASCADE ON UPDATE CASCADE;
