-- CreateTable
CREATE TABLE "pengajuan_alat_baru" (
    "ID_PENGAJUAN" TEXT NOT NULL,
    "NAMA_ALAT" TEXT NOT NULL,
    "JUMLAH_ALAT" TEXT NOT NULL,
    "DESKRIPSI" TEXT NOT NULL,
    "TGL_PENGAJUAN" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pengajuan_alat_baru_pkey" PRIMARY KEY ("ID_PENGAJUAN")
);
