import NavigationTabs from "@/components/navigation/NavigationTabs";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import AuthProvider from "@/lib/AuthProvider";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <AuthProvider>
          <div className="w-full flex flex-col gap-2">
            <NavigationTabs />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
