-- CreateEnum
CREATE TYPE "STATUS_PERMINTAAN" AS ENUM ('PENDING', 'DIVERIFIKASI', 'DITERIMA');

-- CreateTable
CREATE TABLE "alat" (
    "ID_ALAT" TEXT NOT NULL,
    "NAMA_ALAT" TEXT,
    "JUMLAH_ALAT" INTEGER NOT NULL,
    "UNIT_ALAT" TEXT,
    "ALAT_LAYAK" INTEGER NOT NULL DEFAULT 0,
    "ALAT_TIDAK_LAYAK" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "alat_pkey" PRIMARY KEY ("ID_ALAT")
);

-- CreateTable
CREATE TABLE "bahan" (
    "ID_BAHAN" TEXT NOT NULL,
    "NAMA_BAHAN" TEXT,
    "STOCK_BAHAN" INTEGER,
    "UNIT_BAHAN" TEXT,

    CONSTRAINT "bahan_pkey" PRIMARY KEY ("ID_BAHAN")
);

-- CreateTable
CREATE TABLE "permintaan" (
    "ID_PERMINTAAN" TEXT NOT NULL,
    "ID_USER" INTEGER,
    "TGL_PERMINTAAN" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "STATUS" "STATUS_PERMINTAAN" DEFAULT 'PENDING',

    CONSTRAINT "permintaan_pkey" PRIMARY KEY ("ID_PERMINTAAN")
);

-- CreateTable
CREATE TABLE "user" (
    "ID_USER" SERIAL NOT NULL,
    "NAME" TEXT,
    "USERNAME" TEXT,
    "PASSWORD" TEXT,
    "ROLE" TEXT,
    "REGISTER" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_pkey" PRIMARY KEY ("ID_USER")
);

-- CreateTable
CREATE TABLE "detail_permintaan" (
    "ID_DETAIL_PERMINTAAN" TEXT NOT NULL,
    "ID_PERMINTAAN" TEXT NOT NULL,
    "ID_ALAT" TEXT,
    "ID_BAHAN" TEXT,
    "JUMLAH_ALAT" INTEGER,
    "JUMLAH_BAHAN" INTEGER,

    CONSTRAINT "detail_permintaan_pkey" PRIMARY KEY ("ID_DETAIL_PERMINTAAN")
);

-- CreateIndex
CREATE INDEX "permintaan_ID_USER_idx" ON "permintaan"("ID_USER");

-- CreateIndex
CREATE INDEX "detail_permintaan_ID_PERMINTAAN_idx" ON "detail_permintaan"("ID_PERMINTAAN");

-- AddForeignKey
ALTER TABLE "permintaan" ADD CONSTRAINT "permintaan_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "user"("ID_USER") ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "detail_permintaan" ADD CONSTRAINT "detail_permintaan_ID_ALAT_fkey" FOREIGN KEY ("ID_ALAT") REFERENCES "alat"("ID_ALAT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detail_permintaan" ADD CONSTRAINT "detail_permintaan_ID_BAHAN_fkey" FOREIGN KEY ("ID_BAHAN") REFERENCES "bahan"("ID_BAHAN") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detail_permintaan" ADD CONSTRAINT "detail_permintaan_ID_PERMINTAAN_fkey" FOREIGN KEY ("ID_PERMINTAAN") REFERENCES "permintaan"("ID_PERMINTAAN") ON DELETE CASCADE ON UPDATE CASCADE;
